dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: java
      jdk: oraclejdk8
      before_install:
          - chmod +x mvnw
          - chmod +x ./ci/travis_beforeDeploy.sh
      install: skip
      script: env && ./mvnw package -B
      before_deploy:
        - git config --local user.name "Barry Fitzgerald"
        - git config --local user.email "evilconevil2002@gmail.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "target/articulate-1.0.jar"
        skip_cleanup: true
    - stage: deploy to cf
      language: java
      before_install:
        - #permission issue
        - chmod +x mvnw
        - chmod +x ./ci/travis_beforeDeploy.sh
        - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        - sudo apt-get update
        - sudo apt-get install cf-cli
        - sudo apt-get -y install jq
      script:
        - echo "Downloading $RELEASE_TAG"
        - env && ./mvnw package -B
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/pcf-articulate-code/releases/download/$RELEASE_TAG/articulate-1.0.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
      before_script:
        - cf login -a $CF_API_URL -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: $CF_SPACE
      after_deploy:
      provider: bintray
      file: .bintray.desc
      user: mborges-pivotal
      key:
        secure: YA46mZniYwD05sWtrFdlkhidBxE89nhS3fpO8dfeMwrpH3kuQ8n+ctuPKHWCyrNIEiLPAqdXVRocDeDoTTm//+rQiCeTj/PUPBd7xqDc9lXuKZ2CY+eQ1DjW9P+7nj1Ob+xhoF9wIp2Pvlo1xocdmJOP8h6eRHCQ5Xmmr9UDBz/sAvxwM+haICEYfKR/IR3NvZzX0KiUdgjXEAN8I2C4rhYwLuZWrlZ3wdU0T7U81Pfoy4eAlZe4p/AqOlspvusNT6MBzRBUYP0HRQ4goph0N60kGqLkWuMRAGIc4c+CEpHvyE7UXgAZ4eGg3motAvAUmfQNpsm/sKB0NSubn1vXz+vUtGmpmPtl6KSyT7ha0xA7GUof+j6dQBG0q51H2Zg40cKofHXYTPcVxNMVh/cV9zWm+xzhe+6YqbdMETBtJH71dIIFHIeuwV1fferA7Jg70IquozNoJDmPzSeEx68eq3BtmJjKLSyUQFxJK/Dq+g7qqa8TRLMjnKQW1u28X/gUSyPf73cy2kKjYtLWGy3NnWvAlzMSFOPmy7Esk8s0Rge2VPiQPM5qt+/G+vM//Dv9yv8cCedvtHh2e0vH9RjKlhkW61MJMGakOv9dHy2IbOYyt4bpA2qLkZD/hZy7dqPxWOIOSL4HS6QGKyI77lokAXsVGkk+O79MYY9BEL/GRo4=
      dry-run: false
      on:
        tags: true
